name: CI
permissions:
  contents: read
  checks: write

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Maven wrapper is executable
        run: chmod +x mvnw
        
      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run tests
        id: run-tests
        run: ./mvnw -B test --fail-at-end
        continue-on-error: true

      - name: Annotate test failures
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: 'JUnit Tests'
          reporter: java-junit
          path: '**/target/surefire-reports/*.xml'

      - name: Fail on test errors
        if: steps.run-tests.outcome != 'success'
        run: exit 1
